# Generated by Django 3.2.8 on 2021-11-02 10:46

from django.db import migrations, models
import django.db.models.deletion
import dns_ips.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial_20211102'),
        ('dns_ips', '0001_initial_20211102'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsrecord',
            name='tla',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='dns',
                to='inventory.application',
            ),
        ),
        migrations.AddField(
            model_name='dnsnameserver',
            name='source',
            field=models.ForeignKey(
                default=dns_ips.models.default_source_unknown,
                on_delete=django.db.models.deletion.CASCADE,
                to='dns_ips.source',
            ),
        ),
        migrations.AddField(
            model_name='dnsdomain',
            name='dns_nameservers',
            field=models.ManyToManyField(blank=True, related_name='dns_nameservers', to='dns_ips.DNSNameserver'),
        ),
        migrations.AddField(
            model_name='dnsdomain',
            name='register_nameservers',
            field=models.ManyToManyField(blank=True, related_name='register_nameservers', to='dns_ips.DNSNameserver'),
        ),
        migrations.AddField(
            model_name='dnsdomain',
            name='source',
            field=models.ForeignKey(
                default=dns_ips.models.default_source_unknown,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='domain_source',
                to='dns_ips.source',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='ipaddress',
            unique_together={('source', 'name')},
        ),
        migrations.AddIndex(
            model_name='dnsrecordvalue',
            index=models.Index(fields=['active', 'last_seen'], name='dns_ips_dns_active_4a06a4_idx'),
        ),
    ]
