# Generated by Django 3.2.14 on 2022-11-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial_20211102'),
        ('dns_ips', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsrecord',
            name='tla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dns', to='inventory.application', verbose_name='Application'),
        ),
    ]
