# Generated by Django 3.2.18 on 2023-06-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_ips', '0005_deprecate_nameservers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsdomain',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dnsrecord',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
