# Generated by Django 3.2.23 on 2024-01-09 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_finding'),
        ('dns_ips', '0005_deprecate_nameservers'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprange',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.application', verbose_name='Application'),
        ),
    ]
