# Generated by Django 3.2.23 on 2024-01-08 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dns_ips', '0006_iprange_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnsdomain',
            name='register_comment',
        ),
        migrations.RemoveField(
            model_name='dnsdomain',
            name='register_cost_center',
        ),
        migrations.RemoveField(
            model_name='dnsdomain',
            name='register_csc_lock',
        ),
        migrations.RemoveField(
            model_name='dnsdomain',
            name='register_masking',
        ),
        migrations.RemoveField(
            model_name='dnsdomain',
            name='register_portfolio_sections',
        ),
        migrations.RemoveField(
            model_name='dnsdomain',
            name='register_puny_code',
        ),
        migrations.RemoveField(
            model_name='dnsdomain',
            name='register_tld_country',
        ),
        migrations.RemoveField(
            model_name='dnsdomain',
            name='register_tld_region',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='key_supplier',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='point_of_contact',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='website',
        ),
    ]
