# Generated by Django 3.2.25 on 2025-03-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_ips', '0007_remove_unused_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsdomain',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dnsrecord',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
