repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.261'
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: local
    hooks:
      - id: migration-check
        name: migration-check
        entry: python surface/manage.py makemigrations --check --dry-run
        language: system
        files: models.*\.py$
        pass_filenames: false
