# Generated by Django 3.2.12 on 2022-02-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0001_initial_20211102'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerimage',
            name='image',
            field=models.CharField(default='', help_text='Full path to image, including registry', max_length=255),
            preserve_default=False,
        ),
    ]
