# Generated by Django 3.2.23 on 2024-05-28 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_gitsource'),
        ('vulns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SCADependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purl', models.CharField(max_length=255, unique=True)),
                ('dependency_type', models.CharField(max_length=21)),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
                ('is_project', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scan', models.DateTimeField()),
                ('depends_on', models.ManyToManyField(to='sca.SCADependency')),
                ('git_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.gitsource')),
            ],
            options={
                'verbose_name': 'Dependency (SCA)',
                'verbose_name_plural': 'Dependencies (SCA)',
            },
        ),
        migrations.CreateModel(
            name='SCAFindingCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical', models.IntegerField(default=0)),
                ('high', models.IntegerField(default=0)),
                ('medium', models.IntegerField(default=0)),
                ('low', models.IntegerField(default=0)),
                ('eol', models.IntegerField(default=0)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('dependency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sca.scadependency')),
            ],
            options={
                'verbose_name': 'Dependency Finding Counter (SCA)',
                'verbose_name_plural': 'Dependency Finding Counters (SCA)',
            },
        ),
        migrations.CreateModel(
            name='SCAFinding',
            fields=[
                ('finding_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vulns.finding')),
                ('vuln_id', models.CharField(max_length=128)),
                ('published', models.DateTimeField()),
                ('aliases', models.TextField(default='')),
                ('fixed_in', models.TextField(default=None, null=True)),
                ('cvss_vector', models.CharField(default='', max_length=128)),
                ('ecosystem', models.CharField(max_length=20)),
                ('finding_type', models.IntegerField(choices=[(0, 'Vuln'), (1, 'Eol'), (2, 'License')], default=0)),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sca.scadependency')),
            ],
            options={
                'verbose_name': 'Dependency Finding (SCA)',
                'verbose_name_plural': 'Dependency Findings (SCA)',
            },
            bases=('vulns.finding',),
        ),
        migrations.CreateModel(
            name='EndOfLifeDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('cycle', models.CharField(max_length=255)),
                ('release_date', models.DateField(help_text='Release Date for the first release in this cycle')),
                ('latest_release_date', models.DateField(blank=True, help_text='Release Date for the latest release in this cycle', null=True)),
                ('eol', models.DateField(blank=True, help_text='End of Life Date for this release cycle', null=True)),
                ('latest_version', models.CharField(help_text='Latest release in this cycle', max_length=255)),
                ('link', models.URLField(blank=True, default='', help_text='Link to changelog for the latest release, if available', max_length=255)),
                ('lts', models.DateField(blank=True, help_text='Whether this release cycle has long-term-support (LTS)', null=True)),
                ('support', models.DateField(blank=True, help_text='Whether this release cycle has active support', null=True)),
                ('discontinued', models.DateField(blank=True, help_text='Whether this cycle is now discontinued', null=True)),
            ],
            options={
                'verbose_name': 'End of Life Dependency (SCA)',
                'verbose_name_plural': 'End of Life Dependencies (SCA)',
                'unique_together': {('product', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='SCAProject',
            fields=[
            ],
            options={
                'verbose_name': 'Project (SCA)',
                'verbose_name_plural': 'Projects (SCA)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sca.scadependency',),
        ),
        migrations.CreateModel(
            name='SuppressedSCAFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.CharField(max_length=128)),
                ('suppress_reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dependency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sca.scadependency')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suppressed Dependency Finding (SCA)',
                'verbose_name_plural': 'Suppressed Dependency Findings (SCA)',
                'unique_together': {('dependency', 'vuln_id')},
            },
        ),
    ]
