# Generated by Django 3.2.23 on 2024-09-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scafinding',
            name='fixed_in',
            field=models.TextField(default=''),
        ),
    ]
