# Generated by Django 5.2.4 on 2025-10-20 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0002_alter_scafinding_fixed_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='scadependency',
            name='sbom_uuid',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppressedscafinding',
            name='sca_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppressed_findings_project', to='sca.scaproject'),
        ),
    ]
