# Generated by Django 5.2.8 on 2025-11-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0003_scadependency_sbom_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scadependency',
            name='dependencies_list',
            field=models.JSONField(default=list),
        ),
    ]
