# Generated by Django 3.2.12 on 2022-03-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('monitor', models.BooleanField(default=False)),
                ('torify', models.BooleanField(default=False)),
                (
                    'disabled',
                    models.BooleanField(
                        default=False, help_text='only include in scan if specified explicity (not by wildcards)'
                    ),
                ),
                ('big_scope', models.BooleanField(default=False, help_text='include even if scope is big')),
                ('scope_domains_in', models.TextField()),
                ('scope_domains_out', models.TextField()),
                (
                    'ignore_domains',
                    models.TextField(help_text='domains that might be discovered but are never processed'),
                ),
            ],
        ),
    ]
