# Generated by Django 3.2.12 on 2022-03-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbh1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scope',
            name='ignore_domains',
            field=models.TextField(blank=True, help_text='domains that might be discovered but are never processed', null=True),
        ),
        migrations.AlterField(
            model_name='scope',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scope',
            name='scope_domains_in',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scope',
            name='scope_domains_out',
            field=models.TextField(blank=True, null=True),
        ),
    ]
