# Generated by Django 3.2.12 on 2022-04-12 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial_20211102'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbh1', '0003_historicalscope'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEMPScope',
            fields=[
                (
                    'application_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='inventory.application',
                    ),
                ),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('monitor', models.BooleanField(default=False)),
                ('torify', models.BooleanField(default=False)),
                (
                    'disabled',
                    models.BooleanField(
                        default=False, help_text='only include in scan if specified explicity (not by wildcards)'
                    ),
                ),
                ('big_scope', models.BooleanField(default=False, help_text='include even if scope is big')),
                ('scope_domains_in', models.TextField(blank=True, null=True)),
                ('scope_domains_out', models.TextField(blank=True, null=True)),
                (
                    'ignore_domains',
                    models.TextField(
                        blank=True, help_text='domains that might be discovered but are never processed', null=True
                    ),
                ),
            ],
            bases=('inventory.application',),
        ),
        migrations.CreateModel(
            name='HistoricalTEMPScope',
            fields=[
                (
                    'application_ptr',
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name='+',
                        to='inventory.application',
                    ),
                ),
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tla', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('monitor', models.BooleanField(default=False)),
                ('torify', models.BooleanField(default=False)),
                (
                    'disabled',
                    models.BooleanField(
                        default=False, help_text='only include in scan if specified explicity (not by wildcards)'
                    ),
                ),
                ('big_scope', models.BooleanField(default=False, help_text='include even if scope is big')),
                ('scope_domains_in', models.TextField(blank=True, null=True)),
                ('scope_domains_out', models.TextField(blank=True, null=True)),
                (
                    'ignore_domains',
                    models.TextField(
                        blank=True, help_text='domains that might be discovered but are never processed', null=True
                    ),
                ),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'dev_lead',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='inventory.person',
                    ),
                ),
                (
                    'director',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='inventory.person',
                    ),
                ),
                (
                    'director_direct',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='inventory.person',
                    ),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'managed_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='inventory.person',
                    ),
                ),
                (
                    'owned_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='inventory.person',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical temp scope',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
