# Generated by Django 3.2.12 on 2022-04-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbh1', '0005_move_scopes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalscope',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
        migrations.DeleteModel(
            name='HistoricalScope',
        ),
    ]
