# Generated by Django 3.2.12 on 2022-04-12 10:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial_20211102'),
        ('dns_ips', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbh1', '0006_auto_20220412_1017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalTEMPScope',
            new_name='HistoricalScope',
        ),
        migrations.RenameModel(
            old_name='TEMPScope',
            new_name='Scope',
        ),
        migrations.AlterModelOptions(
            name='historicalscope',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical scope'},
        ),
    ]
