# Generated by Django 3.2.12 on 2022-04-12 11:00

from django.db import migrations


def datafix(app, schema):
    D = app.get_model('dns_ips', 'DNSRecord')
    S1 = app.get_model('dns_ips', 'Source')
    ss, _ = S1.objects.get_or_create(name='subfinder')
    S = app.get_model('inventory', 'Application')
    tlas = {x.tla: x.pk for x in S.objects.all()}
    for d in D.objects.filter(tla=None).select_related('source'):
        if d.source.name.startswith('bb1_'):
            tlan = f'BBH1_{d.source.name[4:].upper()}'
            d.tla_id = tlas[tlan]
            d.source = ss
            d.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bbh1', '0007_auto_20220412_1018'),
    ]

    operations = [migrations.RunPython(datafix, reverse_code=migrations.RunPython.noop)]
