# Generated by Django 5.2.4 on 2025-10-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_gitsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='related_to',
            field=models.ManyToManyField(blank=True, help_text='Other findings related to this one', to='inventory.finding'),
        ),
    ]
