# Generated by Django 3.2.25 on 2024-10-26 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField()),
                ('secret_hash', models.CharField(editable=False, max_length=64)),
                ('source', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('false_positive', 'False Positive')], default='new', max_length=20)),
                ('locations', models.JSONField()),
                ('sources', models.JSONField()),
                ('environment', models.CharField(max_length=255)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('short_notes', models.TextField(blank=True)),
                ('team', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('secret_hash', 'source', 'locations')},
            },
        ),
        migrations.CreateModel(
            name='SecretHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_fields', models.JSONField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='secretsmanager.secret')),
            ],
        ),
    ]
