name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  test_image:
    uses: ./.github/workflows/lib_test_image.yml

  tests:
    needs: test_image
    uses: ./.github/workflows/lib_tests.yml

  push:
    needs: tests
    uses: ./.github/workflows/lib_push_image.yml
    # tags: ghcr.io/${{ github.repository }}:latest
    #           cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:builder-cache
    #           cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:builder-cache,mode=max
