name: ci

on:
  push:
    branches:
      - 'mymain'

jobs:
  test_image:
    uses: ./.github/workflows/lib_test_image.yml
    with:
      cache-from: type=registry,ref=ghcr.io/${{ github.repository }}-builder-cache:latest

  tests:
    needs: test_image
    uses: ./.github/workflows/lib_tests.yml

  push:
    needs: tests
    uses: ./.github/workflows/lib_push_image.yml
    with:
      tags: ghcr.io/${{ github.repository }}:${{ github.run_number }},ghcr.io/${{ github.repository }}:latest
      cache-from: |
        type=registry,ref=ghcr.io/${{ github.repository }}-builder-cache:latest
        type=registry,ref=ghcr.io/${{ github.repository }}-builder-cache:${{ github.ref_name }}-amd64
      cache-to: type=registry,ref=ghcr.io/${{ github.repository }}-builder-cache:latest,mode=max
