name: test image

permissions:
  packages: write

on:
  workflow_call:
    inputs:
      build-tag:
        required: true
        type: string
      cache-from:
        required: true
        type: string

jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: dev/Dockerfile
          platforms: linux/amd64
          outputs: type=docker,dest=/tmp/myimage.tar
          tags: ghcr.io/${{ github.repository }}:${{ inputs.build-tag }}
          cache-from: ${{ inputs.cache-from }}
          # specific "cache-to" here as otherwise it would override the latest multi-platform cache with this amd64-only one
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}-builder-cache:${{ inputs.build-tag }}-amd64,mode=max

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: surface-tests
          path: /tmp/myimage.tar
          retention-days: 1
