name: ci dev

on:
  push:
    branches:
      - dev
      - dev-*

jobs:
  test_image:
    uses: ./.github/workflows/lib_test_image.yml
    with:
      cache-from: |
        type=registry,ref=ghcr.io/${{ github.repository }}:builder-cache
        type=registry,ref=ghcr.io/${{ github.repository }}:builder-cache-${{ github.ref_name }}

  tests:
    needs: test_image
    uses: ./.github/workflows/lib_tests.yml

  push:
    needs: tests
    uses: ./.github/workflows/lib_push_image.yml
    with:
      tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      cache-from: |
        type=registry,ref=ghcr.io/${{ github.repository }}:builder-cache
        type=registry,ref=ghcr.io/${{ github.repository }}:builder-cache-${{ github.ref_name }}
        type=registry,ref=ghcr.io/${{ github.repository }}:builder-cache-${{ github.ref_name }}-amd64
      cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:builder-cache-${{ github.ref_name }},mode=max
