name: integration testing

on:
  workflow_call:

jobs:
  doit:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome

    steps:
      - uses: actions/checkout@v4
      
      - name: install mysql dependencies
        run: sudo apt-get install python3-dev libmysqlclient-dev build-essential pkg-config
      
      - name: Set-up environment
        run: pip install -r surface/requirements_test.txt

      - name: Run test suite
        run: pytest -v e2e
