name: tests

on:
  workflow_call:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install black
      run: pip install black==22.1.0

    - name: Style check
      run : make style_check

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        database:
        - db: mysql
          url: mysql://root:root@127.0.0.1:8877/surface
        - db: postgresql
          url: psql://root:root@127.0.0.1:8878/surface

    services:
      mysql:
        image: mysql:5
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 8877:3306
        # needed because the container does not provide a healthcheck
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries=5
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: surface
        ports:
        - 8878:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Download artifacts (Docker images) from previous workflows
        uses: actions/download-artifact@v2
        with:
          name: surface-tests
          path: /tmp

      - name: Load Docker images from previous workflows
        run: |
          docker load --input /tmp/myimage.tar

      - name: run tests
        run: docker run --network host -e SURF_DATABASE_URL=${{ matrix.database.url }} --rm ghcr.io/${{ github.repository }}:${{ github.ref_name }} pytest -n4

    # - uses: codecov/codecov-action@v2
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     fail_ci_if_error: true
